# Theme settings
doks:
    baseurl:
    color_theme: green
    header:
        logo:
            text: Bits & Basteln
            image:
        nav:
            - item_name: Item 1
              item_url: '#'
            - item_name: Item 2
              item_url: '#'
            - item_name: Item 3
              item_url: '#'
    footer:
        content:
            logo:
                text: Bits & Basteln
                image:
            copyright: Copyright &copy; 2019. - Neue Nachbarschaft Moabit e.V. <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: 'https://www.facebook.com/neuenachbarschaftmoabit/'
            - network_name: github
              profile_url: 'https://github.com/bits-und-basteln/'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
